### 指定日志配置文件
log:
  url: /shiroDemo/

server:
  port: 9090
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/shiroDemo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 19941128ya
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 3000
      login-timeout: 5

  ## redis配置
  redis:
    # redis服务端口号
    port: 6379
    # redis服务地址
    host: 127.0.0.1
    # lettuce连接池配置
    lettuce:
      pool:
        # 连接池最大阻塞等待时间
        max-wait: 1000ms
        # 最大空闲数
        max-idle: 8
        # 最小空闲数
        min-idle: 1
        # 最大连接数
        max-active: 8
      # 关闭超时时间
      shutdown-timeout: 100ms
    timeout: 10000ms

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.hezhan.shirodemo.entity
  configuration:
    # 取消驼峰下划线转换
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      # 第二种方法，在配置文件里设置update时的字段策略，这里选择ignored，即忽略检测null字段，即可进行全字段更新
#      update-strategy: ignored